### PR TITLE
implementation of modular serializer/deserializer

### PR DESCRIPTION
**Pull request by angleto**
Refactored serializer/deserializers classes in order to be overridden and passed to the Whatsapp constructors, for instance:
```java
        Serializers serializers = Serializers.builder()
                .serializer(new DefaultControllerSerializerProvider())
                .deserializer(new DefaultControllerDeserializerProvider())
                .build();
        var whatsapp = Whatsapp.lastConnection(options, serializers)
                .addLoggedInListener(api -> {
                    System.out.println("Connected: " + api.store().userCompanionJid());
                    api.sendMessage(ContactJid.of("393495089819"), "test");
                })
```

My java is a bit rusty and there are issues with the lombok generated classes, hopefully you can help to fix this (this issue is reproducible even without my changes).

### CODE REVIEW

**Comment by Auties00** [comment]
> Refactored serializer/deserializers classes in order to be overridden and passed to the Whatsapp constructors, for instance:
> 
> ```java
>         Serializers serializers = Serializers.builder()
>                 .serializer(new DefaultControllerSerializerProvider())
>                 .deserializer(new DefaultControllerDeserializerProvider())
>                 .build();
>         var whatsapp = Whatsapp.lastConnection(options, serializers)
>                 .addLoggedInListener(api -> {
>                     System.out.println("Connected: " + api.store().userCompanionJid());
>                     api.sendMessage(ContactJid.of("393495089819"), "test");
>                 })
> ```
> 
> My java is a bit rusty and there are issues with the lombok generated classes, hopefully you can help to fix this (this issue is reproducible even without my changes).

Hello, thanks for opening a PR!
Currently serializers and deserializers get registered through the SPI api. Is there any reason why you propose to pass it explicitly instead? 
Also I would have personally put the serializer option in the WhatsappOptions class, is there any reason for not doing so in your opinion?

**Comment by angleto** [comment]
Hello,
1) I think is more flexible to specialize and pass the serializers, in this way you could cleanly use more than one kind of serializer specialization, for different data stores, on the same project.
2) right, my first though was as well of putting the serializers inside the WhatsappOptions and is probably the correct choice, I made the assumption you didn't want it there since you didn't put it there already :)
As said, I'm not proficient in java (I develop mainly in scala) and there is some issue with Lombok that I wasn't unable to solve.
Just a note, I tend to not use preview features, because they tend to change and tend to require additional work of refactoring. On the other side I understand that is nice sometime to avoid boilerplate code :)
The project is really good in any case! So compliments and thanks for your effort!

**Comment by Auties00** [comment]
> Hello,
> 
> 1. I think is more flexible to specialize and pass the serializers, in this way you could cleanly use more than one kind of serializer specialization, for different data stores, on the same project.
> 2. right, my first though was as well of putting the serializers inside the WhatsappOptions and is probably the correct choice, I made the assumption you didn't want it there since you didn't put it there already :)
>    As said, I'm not proficient in java (I develop mainly in scala) and there is some issue with Lombok that I wasn't unable to solve.
>    Just a note, I tend to not use preview features, because they tend to change and tend to require additional work of refactoring. On the other side I understand that is nice sometime to avoid boilerplate code :)
>    The project is really good in any case! So compliments and thanks for your effort!

I understand. Can you check the latest commit I pushed to master?
It actually makes sense to have the serializer and deserializer in the options to avoid the whole isBest thing, I should have thought about it earlier.

**Comment by angleto** [comment]
@Auties00 looks good to me!

**Comment by angleto** [comment]
we can close this PR.

**Pull request closed without merging**
